[package]
name = "esp32-rtv"
version = "0.1.0"
authors = ["rectalogic@rectalogic.com"]
edition = "2024"
resolver = "3"
rust-version = "1.93"

[[bin]]
name = "esp32-rtv"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
thiserror = "2.0.18"
anyhow = "1.0.104"
mipidsi = "0.10.0"
embedded-graphics = "0.8.2"
static_cell = "2.1.1"
es8311 = "0.1.1"

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_new_jpeg", version = "^1.0.0" }
bindings_header = "components/esp_new_jpeg/bindgen.h"
bindings_module = "esp_new_jpeg"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "thorrak/esp_wifi_config", version = "^0.1.0" }
bindings_header = "components/esp_wifi_config/bindgen.h"
bindings_module = "esp_wifi_config"
