[workspace]
members = ["xtask"]

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"

[package]
name = "esp32-rtv"
version = "0.1.0"
authors = ["rectalogic@rectalogic.com"]
edition.workspace = true
license.workspace = true
rust-version = "1.93"

[[bin]]
name = "esp32-rtv"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[workspace.dependencies]
anyhow = "1.0.104"

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
anyhow = { workspace = true }
thiserror = "2.0.19"

[build-dependencies]
embuild = "0.33"

[package.metadata.esp-idf-sys]
esp_idf_sdkconfig_defaults = ["sdkconfig.defaults", "components/gen_bmgr_codes/board_manager.defaults"]

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_board_manager", version = "*" }

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = "components/gen_bmgr_codes"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = "components/video_player"
bindings_header = "components/video_player/bindings.h"
bindings_module = "video_player"
